layout_spectrum: 0.1801429
typography_spectrum: 0.616658
color:
  saturation: 0.6043649
  lightness: 0.6937756
  brandStrength: 0.6131976
  rhythmicContrast: 0.2631771
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Ama Llulla Expat Services
